version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www

  mysql:
    image: mysql:latest
    env_file:
      - .env.test
    ports:
      - "3307:3306"
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "--silent"]
    #   interval: 10s
    #   retries: 3
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DATABASE: ress_rela_sy_test
    #   MYSQL_USER: mysqluser
    #   MYSQL_PASSWORD: mdpmysqluser
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: