# .github/workflows/ci.yml
name: Run Symfony Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Build and start services with Docker Compose
      run: docker-compose -f docker-compose.test.yml up -d --build

    - name: Wait for MySQL to be ready
      run: |
        docker-compose exec mysql sh -c 'until mysqladmin ping --silent; do sleep 1; done'

    - name: Install dependencies
      run: docker-compose exec app composer install --prefer-dist --no-progress --no-suggest

    - name: Create database
      run: docker-compose exec app php bin/console --env=test doctrine:database:create

    - name: Create tables
      run: docker-compose exec app php bin/console --env=test doctrine:schema:create

    - name: Load fixtures
      run: docker-compose exec app php bin/console --env=test doctrine:fixtures:load --no-interaction

    - name: Run PHPUnit tests
      run: docker-compose exec app ./bin/phpunit --testdox --coverage-text

    - name: Stop and remove Docker Compose services
      run: docker-compose down